name = "Calculator"
uuid = "b5585f7e-79a1-4ba3-8dc5-4e8971201376"
authors = ["Mark Nalley <mnalley95@gmail.com> and contributors"]
version = "0.1.0"

[deps]
SaferIntegers = "88634af6-177f-5301-88b8-7819386cfa38"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
